dev:
  debug: true
  voice_enabled: true
  log_dir: logs/
  gui_theme: dark
  language: es
  transcription_engine: whisper
  tts_engine: pyttsx3

  # → NUEVO BLOQUE de Data Collection
  data_collection:
    enabled: true            # activá/desactivá recolección
    interval_sec: 60         # cada cuánto (en segundos)
    metrics:
      - cpu_usage
      - ram_usage
      - disk_io
      - network_io
      - command_log
      - ui_interaction
      - error_log
      - ambient_noise

  # → NUEVO BLOQUE de Forced Load
  forced_load:
    enabled: true            # forzar uso extra
    cpu_load_percent: 50     # consumir +20% de CPU en idle
    mem_load_mb: 100         # retener +100 MB en idle

prod:
  debug: false
  voice_enabled: true
  log_dir: /var/log/jarvis/
  gui_theme: light
  language: es
  transcription_engine: whisper
  tts_engine: elevenlabs

  data_collection:
    enabled: true
    interval_sec: 30
    metrics:
      - cpu_usage
      - ram_usage
      - disk_io
      - network_io
      - command_log
      - ui_interaction
      - error_log

  forced_load:
    enabled: true
    cpu_load_percent: 10
    mem_load_mb: 50
